name: MAUI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
    DOTNETVERSION: 8.0.x

jobs:
  buildAndroidAndiOS:
    runs-on: macos-os-15
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:  '${{env.DOTNETVERSION}}'

      - name: Install .NET MAUI
        run: dotnet workload install maui
    
      - name: Restore dependencies
        run: dotnet restore

      # iOS SECTION
      - name: Setup iOS Certificate
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Download iOS Provisioning Profile
        uses: poad/apple-provisioning-profiles-downloader@v1.0.8
        with: 
          bundle-id: 'com.ioddfinder'
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Build iOS App
        run: dotnet publish -f net8.0-ios -c Release -p:ApplicationVersion=${{ github.run_number }}

      - name: Publish iOS to TestFlight
        uses: Apple-Actions/upload-testflight-build@v1
        with:
          app-path: ./IODDFinder/bin/Release/net8.0-ios/ios-arm64/publish/IODDFinder.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      # iOS SECTION
      # - name: Build Android App
      #   run:  dotnet publish -f net8.0-android -c Release
